pages:
  - 主页: 'index.md'
  - 入门(Getting started):
    - OpenGL: '01 Getting started/01 OpenGL.md'
    - 创建一个窗口: '01 Getting started/02 Creating a window.md'
    - Hello Window: '01 Getting started/03 Hello Window.md'
    - Hello Triangle: '01 Getting started/04 Hello Triangle.md'
    - 坐标系统: '01 Getting started/08 Coordinate Systems.md'
    - 复习: '01 Getting started/10 Review.md'

site_name: LearnOpenGL-CN

markdown_extensions:
  - admonition
  - smarty
  - sane_lists

extra_css:
  - css/code_fixer.css
